import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { cloudflare } from '@cloudflare/vite-plugin';
import { reactRouter } from '@react-router/dev/vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import oxlintPlugin from 'vite-plugin-oxlint';
import babel from 'vite-plugin-babel';
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, loadEnv } from 'vite';
import dedent from 'dedent';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** Load `.env` from monorepo root (single file for `VITE_*`); no URL defaults in code. */
const monorepoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

const ReactCompilerConfig = {
  /* ... */
};

const shouldRunOxlint = process.env.ZERO_DISABLE_OXLINT !== '1';

const plugins = [
  ...(shouldRunOxlint ? [oxlintPlugin()] : []),
  reactRouter(),
  cloudflare(),
  babel({
    exclude: [/node_modules/, /[\\/]paraglide[\\/]/],
    filter: /\.[jt]sx?$/,
    babelConfig: {
      presets: ['@babel/preset-typescript'], // if you use TypeScript
      plugins: [['babel-plugin-react-compiler', ReactCompilerConfig]],
      compact: false,
    },
  }),
  tsconfigPaths(),
  tailwindcss(),
  {
    name: 'add-headers',
    applyToEnvironment: (env) => env.name === 'client',
    generateBundle() {
      this.emitFile({
        fileName: '_headers',
        type: 'asset',
        source: dedent`
          # Autogenerated

          /assets/*
            ! Cache-Control
              Cache-Control: public, immutable, max-age=31536000
        `,
      });
    },
  },
  paraglideVitePlugin({
    project: './project.inlang',
    outdir: './paraglide',
    strategy: ['cookie', 'baseLocale'],
  }),
];

export default defineConfig(({ mode }) => {
  const loaded = loadEnv(mode, monorepoRoot, '');
  const zeroDemoMode = process.env.ZERO_DEMO_MODE ?? loaded.ZERO_DEMO_MODE ?? '';

  return {
    envDir: monorepoRoot,
    define: {
      'import.meta.env.ZERO_DEMO_MODE': JSON.stringify(zeroDemoMode),
    },
    plugins: [...plugins],
    server: {
      port: 3000,
      warmup: {
        clientFiles: ['./app/**/*', './components/**/*'],
      },
    },
    esbuild: {
      pure: ['console.log'],
    },
    build: {
      sourcemap: false,
    },
    resolve: {
      alias: {
        tslib: 'tslib/tslib.es6.js',
      },
    },
  };
});
